# Generated by Django 4.1.3 on 2022-12-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0002_wreck_beavertail_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wreck',
            name='beavertail_link',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='wreck',
            name='wreckhunter_link',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='wreck',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
